version: "4"
services:
  api:
    build: .
    command:
      - uvicorn
      - main:app
      - --host=0.0.0.0
      - --port=1234
    ports:
    - "1234:1234"
    volumes:
      - .:/code
    depends_on:
      - database
  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: